format = """
[┌> ](#856b30)$os$username[](#856b30)$directory$python$git_branch$git_status
[│](#856b30)
[└──────>](#856b30) 
"""

# Disable the blank line at the start of the prompt
add_newline = true

[username]
show_always = true
style_user = "bg:#856b30 fg:#ffffff"
style_root = "bg:#9A348E"
#format = '[$user ]($style)'
format = '[dont chase goals, chase a character]($style)'
disabled = false

[directory]
style = "fg:#cdd6f4"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[python]
symbol = "󱔎 "
format = '[($symbol $virtualenv )]($style)'

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
style = "fg:#cf6784"
symbol = " "
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#cf6784"
format = '[$all_status $ahead_behind ]($style)'
